require('user.options')
require('user.plugins')
require('user.cmp')
require('user.lsp')
require('user.telescope')
require('user.nvimtree')
require('user.treesitter')
require('user.statusline')
require('user.colorscheme')
require('user.keymaps')
-- require('user.dashboard')
require('user.post')
